site_name: farmerboy's CP Blogs
docs_dir: src
repo_url: https://github.com/farmerboy95/CPBlogs
repo_name: farmerboy95/CPBlogs
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.jpg
  favicon: assets/images/logo.jpg
  features:
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 farmerboy

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/farmerboy95
  analytics:
    provider: google
    property: G-W9EFM7GCX7
    feedback:
      title: Bài viết này có tốt không?
      ratings:
        - icon: material/thumb-up-outline
          name: Bài viết rất hay
          data: 1
          note: >-
            Cảm ơn phản hồi tích cực của bạn!
        - icon: material/thumb-down-outline
          name: Bài viết cần được cải thiện
          data: 0
          note: >- 
            Cảm ơn phản hồi của bạn! Nếu có thời gian mong bạn vui lòng giúp mình cải thiện bài viết bằng cách thêm issue vào 
            <a href="https://github.com/farmerboy95/CPBlogs/issues" target="_blank">GitHub</a> của trang này.

plugins:
  - literate-nav:
      nav_file: navigation.md
  - search
  # - git-authors:
  #     show_contribution: true
  #     exclude:
  #       - index.md
  #       - navigation.md
  # - git-revision-date-localized:
  #     type: custom
  #     custom_format: "%d/%m/%Y %H:%M (GMT%Z)"
  #     timezone: Asia/Ho_Chi_Minh
  #     locale: vi
  #     enable_creation_date: true
  #     enabled: true
  #     exclude:
  #       - index.md
  #       - navigation.md
