site_name: farmerboy's CP Blogs
docs_dir: src
repo_url: https://github.com/farmerboy95/CPBlogs
repo_name: farmerboy95/CPBlogs
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.jpg
  favicon: assets/images/logo.jpg
  features:
    - navigation.tabs
    - navigation.top
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 farmerboy

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/farmerboy95
  analytics:
    provider: google
    property: G-W9EFM7GCX7

plugins:
  - literate-nav:
      nav_file: navigation.md
  - search
